version: '3'

services:

    app:
      build: ./nodejs/
      container_name: node-app
      command: node index.js
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      tty: true
      networks:
        - node-network
      ports: 
        - "3000:3000"
      depends_on:
        - db

    db:
      platform: linux/amd64
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - node-network

networks:
  node-network:
    driver: bridge
